### PR TITLE
refactor: centralize script conditions from state modules

### PR DESCRIPTION
**Pull request by ultijlam**
Move all script conditions defined in state modules into the
`conditions` module.

Leave the `Variables` module alone as the script conditions in it
seem to be unused and misnamed.

### CODE REVIEW

**Comment by ultijlam** [comment]
This pullup has a merge conflict with #999. I can resolve the conflicts once either one is merged into the master branch.

**Comment by Sidoine** [comment]
What is the point of this change?

**Comment by ultijlam** [comment]
It moves the remaining script conditions from the other modules to `conditions` module and reduces the dependencies between some of the modules that were there solely to provide information for the script conditions.

**Comment by ultijlam** [comment]
I wanted to leave the state module as just doing their one thing well and exporting useful information through their API. It makes it easier to refactor some of the modules because this change reduces the number of links between them, e.g., changing the `Health` doesn't actually impact the `Stagger` module in any way.

**Comment by Sidoine** [comment]
I moved the conditions to the state module because the conditions.ts file was way too large. Maybe the conditions should be split in several classes.

**Comment by ultijlam** [comment]
> I moved the conditions to the state module because the conditions.ts file was way too large. Maybe the conditions should be split in several classes.

I had originally created a branch to move all of the script conditions out of the `conditions.ts` file and into each state module, but I didn't like that I had to introduce extra dependencies (sometimes circular dependencies) between modules just to accommodate the move. I felt that was a sign that it was the wrong way to go.

I think splitting up the `conditions.ts` file is fine.  I'm think we should actually just make a `conditions` directory and just split out each condition or group of related conditions into separate files that clearly spells out via `import` statements on which modules are needed to make that script condition work. If you think this is worth doing, I can do the work on a separate branch. In the meantime, I think this pullup is still worthwhile because of the reduced linkage between the modules, and I would build the new branch for *one-file-per-condition* off of this pullup.

**Comment by ultijlam** [comment]
Having lots of little files does impact addon loading time, which is noticeable every time you see a loading screen in-game, so we could split into a smaller set of files. But it feels weird to `import` from `OvaleConditionsAtoE`, `OvaleConditionsFtoJ`, etc. Why is it bad again to have one big file containing all of the conditions? Does it bump up against a limit from the game client or Lua environment?

**Comment by ultijlam** [comment]
I have a different idea for splitting up the `conditions.ts` file that might work better. We could split script conditions into separate files based on which state modules are needed to be imported in order to make them work.  That would nicely document which script conditions require which state modules by physically partitioning them, and we could then use that information to enable/disable unused modules with the goal of speeding up Ovale overall.  What are your thoughts on this idea?

**Comment by Sidoine** [comment]
You're right that a state module should be disabled altogether if none of its conditions are used. It's why I think the conditions should be kept within the state and maybe the register method should take the module as an extra parameter. 

I see that you had problems with extra dependencies but I guess it means that in this case some code should be moved around to avoid this (for example from a state module to an engine module).

**Comment by ultijlam** [comment]
I'm going to close this pullup and go with your idea. I will resurrect my old branch that had begun to disperse all of the script conditions in `conditions.ts` into the various state modules.  The full plan has the following steps:
1. Put every condition into a corresponding state module.
2. Ensure that each state module does the right thing when disabled and enabled in-game.
3. Teach the script conditions registry about which state module each script condition is a part of.
4. Teach `wowts/tsaddon` about how to disable a module or an addon by running the appropriate class method.
5. Teach `engine/compile` to disable all modules and enable only the ones needed by script conditions detected during compilation.
I will reproduce this comment as a discussion topic.

**Pull request closed without merging**
