### PR TITLE
adding condition nottalentpoints

### PR DESCRIPTION
**Pull request by Morl0ck**

### CODE REVIEW

**Comment by kevindesmet** [comment]
What are you trying to accomplish with this?
Can you give an example of the APL and how it would translate into the script?

**Comment by Morl0ck** [comment]
In the T19H of the Assassination Rogue there is this action:

`envenom,if=combo_points>=cp_max_spend-talent.master_poisoner.enabled|(talent.elaborate_planning.enabled&combo_points>=3+!talent.exsanguinate.enabled&buff.elaborate_planning.remains<2)`

`3+!talent.exsanguinate.enabled` gets translated to `3 + { not TalentPoints(exsanguinate_talent) }` which causes it to not work.

**Comment by Sidoine** [comment]
It would be better that talent.exsanguinate.enabled is translated to { TalentPoints(exsanguinaite_talent) > 0 }

**Comment by Morl0ck** [comment]
I dont understand Sidoine. 
Its doing an arithmetic operation based on the whether the user has the talent or not.
3 + 1 if the character doesnt have the talent, or 3 + 0 if the character has the talent.

**Comment by ShmooDude** [comment]
Have you tried `Talent(exsanguinaite_talent no)`  That should be the same as this added code.

**Comment by Morl0ck** [comment]
Yes that worked Shmoo. Let me change modify the pull request.

**Pull request merged**
