### PR TITLE
Updates and Bug Fixes to Protection Paladin script based on latest SimC (11/6/2016)

### PR DESCRIPTION
**Pull request by tehmufifnman**
… 11/6/2016

Added missing avengers shield action based on missing crusaders judgement talent definition
Added multiple missing shield of the righteous actions based on missing seraphim talent definition
Updated consecration action conditions based on missing crusaders judgement talent definition
Updated multiple hammer of the righteous actions based on missing crusaders judgement talent definition
Updated blinding light auction based on missing crusaders judgement talent definition
Updated required symbols
Added missing seraphim talent definition
Added missing crusaders judgement definition

### CODE REVIEW

**Comment by kevindesmet** [comment]
@tehmufifnman are you aware that changes done to the scripts get overwritten when new profiles get pulled from simc?

Look for these lines in ovale_paladin.lua
```
-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED.
-- ANY CHANGES MADE BELOW THIS POINT WILL BE LOST.
```

**Comment by tehmufifnman** [comment]
Ya I am, I just momentarily forgot.

The pre-modified script was generated from the same profile, but because of the missing talent definitions there multiple missing actions and conditions.

So I guess technically I regenned the script as if it was a new SimC script?

I am not sure what the proper course of action is in that case. :)

**Comment by kevindesmet** [comment]
Well, you could also commit your modified simc script in scripts/ folder and regenerate the script using utils/generate.lua.

See #152 when we finally get to answer the question how to properly regenerate scripts :)

**Comment by tehmufifnman** [comment]
I didn't modify the simc script.  The conversions process from the existing simc script to Ovale wasn't working due to the missing talent definitions on the paladin_spells.  The changes to the Ovale paladin script were a result of importing the existing simc script after fixing the missing definitions in Ovale.

**Pull request merged**
